language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.4

install:
  - travis_retry composer install --no-interaction --no-suggest

script:
  - composer test-coverage

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

notifications:
  email: false